"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface InvoiceDoc {
  number: string;
  type: "invoice" | "quotation";
  status: string;
  issue_date: string;
  due_date: string;
  business: { name: string; city?: string; currency: string };
  customer: { name: string; company?: string | null; email?: string | null; phone?: string | null; address?: string | null; city?: string | null };
  items: { name: string; qty: number; price: number }[];
  subtotal: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  amount_paid: number;
  notes?: string | null;
}

const money = (n: number) => "INR " + n.toLocaleString("en-IN");

export function generateInvoicePdf(doc: InvoiceDoc) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  const M = 40;
  const ink = [27, 37, 89] as const;
  const muted = [120, 128, 150] as const;

  // Header
  pdf.setFillColor(...ink);
  pdf.rect(M, 40, 10, 10, "F");
  pdf.rect(M + 13, 40, 10, 10, "F");
  pdf.rect(M, 53, 10, 10, "F");
  pdf.rect(M + 13, 53, 10, 10, "F");
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.setTextColor(...ink);
  pdf.text(doc.business.name, M + 34, 56);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(...muted);
  pdf.text(doc.business.city ?? "India", M + 34, 70);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.setTextColor(...ink);
  pdf.text(doc.type === "quotation" ? "QUOTATION" : "INVOICE", W - M, 56, { align: "right" });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(...muted);
  pdf.text(`#${doc.number}`, W - M, 72, { align: "right" });
  pdf.text(`Issued ${doc.issue_date}`, W - M, 86, { align: "right" });
  pdf.text(`Due ${doc.due_date}`, W - M, 100, { align: "right" });

  // Bill to
  pdf.setDrawColor(230, 230, 226);
  pdf.line(M, 120, W - M, 120);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(...muted);
  pdf.text("BILLED TO", M, 140);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(...ink);
  pdf.text(doc.customer.name, M, 156);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(...muted);
  let y = 170;
  for (const line of [doc.customer.company, doc.customer.email, doc.customer.phone, [doc.customer.address, doc.customer.city].filter(Boolean).join(", ")].filter(Boolean)) {
    pdf.text(String(line), M, y);
    y += 13;
  }

  // Items table
  autoTable(pdf, {
    startY: Math.max(y + 10, 200),
    head: [["Item", "Qty", "Unit price", "Amount"]],
    body: doc.items.map((it) => [it.name, String(it.qty), money(it.price), money(it.price * it.qty)]),
    theme: "plain",
    headStyles: { textColor: muted as any, fontSize: 8, fontStyle: "bold", cellPadding: { top: 6, bottom: 6, left: 4, right: 4 } },
    bodyStyles: { textColor: [40, 45, 70], fontSize: 10, cellPadding: { top: 8, bottom: 8, left: 4, right: 4 } },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
    margin: { left: M, right: M },
    didDrawPage: () => {},
  });

  let ty = (pdf as any).lastAutoTable.finalY + 16;
  const rightX = W - M;
  const labelX = W - M - 150;
  const rows: [string, string][] = [
    ["Subtotal", money(doc.subtotal)],
    [`Tax (${doc.tax_rate}%)`, money(doc.tax_amount)],
  ];
  pdf.setFontSize(10);
  for (const [label, val] of rows) {
    pdf.setTextColor(...muted);
    pdf.text(label, labelX, ty);
    pdf.setTextColor(40, 45, 70);
    pdf.text(val, rightX, ty, { align: "right" });
    ty += 16;
  }
  pdf.setDrawColor(230, 230, 226);
  pdf.line(labelX, ty - 4, rightX, ty - 4);
  ty += 8;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.setTextColor(...ink);
  pdf.text("Total due", labelX, ty);
  pdf.text(money(doc.total - doc.amount_paid), rightX, ty, { align: "right" });

  // Footer
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  pdf.setTextColor(...muted);
  pdf.text(
    doc.notes || "Generated by Vyuha OS. Please make payment by the due date. Thank you for your business.",
    M,
    pdf.internal.pageSize.getHeight() - 40,
    { maxWidth: W - 2 * M }
  );

  pdf.save(`${doc.number}.pdf`);
}
