"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface ReportDoc {
  title: string;
  businessName: string;
  period: string;
  generatedOn: string;
  metrics: { label: string; value: string }[];
  sections?: { heading: string; rows: [string, string][] }[];
}

export function generateReportPdf(doc: ReportDoc) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  const M = 40;
  const ink = [27, 37, 89] as const;
  const muted = [120, 128, 150] as const;

  pdf.setFillColor(...ink);
  [0, 13].forEach((dx) => [0, 13].forEach((dy) => pdf.rect(M + dx, 40 + dy, 10, 10, "F")));
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.setTextColor(...ink);
  pdf.text(doc.businessName, M + 34, 56);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(...muted);
  pdf.text("Generated by Vyuha OS", M + 34, 70);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.setTextColor(...ink);
  pdf.text(doc.title, M, 110);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(...muted);
  pdf.text(`${doc.period} · ${doc.generatedOn}`, M, 126);

  autoTable(pdf, {
    startY: 150,
    head: [["Metric", "Value"]],
    body: doc.metrics.map((m) => [m.label, m.value]),
    theme: "striped",
    headStyles: { fillColor: ink as any, textColor: [255, 255, 255], fontSize: 10 },
    bodyStyles: { fontSize: 11, cellPadding: 8 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: M, right: M },
  });

  let y = (pdf as any).lastAutoTable.finalY + 20;
  for (const section of doc.sections ?? []) {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(...ink);
    pdf.text(section.heading, M, y);
    autoTable(pdf, {
      startY: y + 8,
      body: section.rows,
      theme: "plain",
      bodyStyles: { fontSize: 10, cellPadding: 5, textColor: [40, 45, 70] },
      columnStyles: { 1: { halign: "right" } },
      margin: { left: M, right: M },
    });
    y = (pdf as any).lastAutoTable.finalY + 20;
  }

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  pdf.setTextColor(...muted);
  pdf.text("This report was generated automatically by Vyuha OS from live business data.", M, pdf.internal.pageSize.getHeight() - 40);

  pdf.save(`${doc.title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
