// Emits supabase/seed.sql from the same generator that powers demo mode.
// Run: npm run gen:seed-sql

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildSeedDatabase } from "../lib/db/seed";

const db = buildSeedDatabase();

const JSONB_COLS = new Set(["tags", "items", "comments"]);
const TABLE_ORDER = [
  "businesses", "users", "categories", "suppliers", "warehouses", "products",
  "customers", "leads", "deals", "orders", "order_items", "invoices",
  "payments", "expenses", "stock_movements", "purchase_orders", "employees",
  "attendance", "leave_requests", "payroll", "projects", "tasks", "documents",
  "knowledge_base_files", "notifications", "audit_logs",
];

function sqlValue(col: string, v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (JSONB_COLS.has(col)) return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
}

let out = `-- Vyuha OS seed data — generated by scripts/gen-seed-sql.ts.
-- Identical to the demo-mode dataset. Run after schema.sql.
-- NOTE: users.auth_id is null in seed data; sign up with the emails below and
-- link auth_id, or let the app's onboarding create your own business instead.

`;

for (const table of TABLE_ORDER) {
  const rows = db[table];
  if (!rows?.length) continue;
  out += `delete from ${table};\n`;
}
out += "\n";

for (const table of TABLE_ORDER) {
  const rows = db[table];
  if (!rows?.length) continue;
  const cols = Object.keys(rows[0]);
  out += `insert into ${table} (${cols.join(", ")}) values\n`;
  out += rows
    .map((r) => `  (${cols.map((c) => sqlValue(c, (r as any)[c])).join(", ")})`)
    .join(",\n");
  out += ";\n\n";
}

const dest = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(dest, out);
console.log(`Wrote ${dest}`);
for (const table of TABLE_ORDER) {
  console.log(`  ${table}: ${db[table]?.length ?? 0} rows`);
}
